#!/bin/sh
# (C) 2014, "/etc/rc.d/crond", cgraf, GPL 
case $1 in
 restart) kill "$(( $(cat /var/run/crond.pid) + 1 ))"
          crond -c /cron & echo "$!">/var/run/crond.pid
          ;;
  status) cat /var/run/crond.pid && echo crond running
          ;;
   start) if [ -e /cron ] 
          then echo ok
          else mkdir -p /cron/cron.hourly /cron/cron.weekly /cron/cron.minutely
               mkdir -p /cron/cron.daily /cron/cron.monthly
               echo "PATH=/sbin">>/cron/root
               echo "*  * *  * * /sbin/run-parts /cron/cron.minutely">>/cron/root
               echo "1  * *  * * /sbin/run-parts /cron/cron.hourly">>/cron/root
               echo "6  3 *  * * /sbin/run-parts /cron/cron.daily">>/cron/root
               echo "10 4 *  * 2 /sbin/run-parts /cron/cron.weekly">>/cron/root
               echo "12 3 20 * * /sbin/run-parts /cron/cron.monthly">>/cron/root
          fi
          crond -c /cron & echo "$!" > /var/run/crond.pid
          ;;
    stop) kill "$(( $(cat /var/run/crond.pid) + 1 ))"
          echo >/var/run/crond.pid
          ;; 
       *) echo "/etc/rc.d/crond [start|stop|status|restart]" 
          ;;
esac
