#!/bin/sh
case $1 in
 restart) /sbin/kill "$(cat /var/run/dropbear.pid)"
          sleep 1 ; dropbear -g -w -R -P
          ;;
  status) cat /var/run/dropbear.pid && echo dropbear running
          ;;
   start) dropbear -g -w -R -P
          ;;
    stop) /sbin/kill "$(cat /var/run/dropbear.pid)"
          ;;
       *) echo "dropbear [start|stop|status|restart]"
          ;;
esac
