#!/bin/sh
case $1 in
 restart) /sbin/kill "$(( $(cat /var/run/httpd.pid) + 1 ))"
          /sbin/httpd -h /www & echo "$!">/var/run/httpd.pid
          ;;
  status) cat /var/run/httpd.pid && echo httpd running
          ;;
   start) [ -d /www ] || (mkdir -p /www ; echo "It works">/www/index.html)
          httpd -h /www & echo "$!" >/var/run/httpd.pid
          ;;
    stop) /sbin/kill "$(( $(cat /var/run/httpd.pid) + 1 ))"
          ;;
       *) echo "httpd [start|stop|status|restart]"
          ;;
esac
